# URL where a Lotus instance's API can be found.
# Default:  http://127.0.0.1:1234/
lotusUrl = "http://127.0.0.1:1234/"

# Absolute path to the data dir (where retrieved CIDs are stored)
# Default:  ~/.retrieval_client_data
dataDir = "/Users/mwg/code/RetrievalPocJs/miner1/data"

# Array of CIDs with custom retrieval costs. (CIDs will 
# be ignored if the corresponding file isn't in dataDir.)
# Default: [{'cid':'*','pricePerByte':0.0000000005}]

# The wildcard CID governs CIDs found in dataDir but not
# in this array.
[[cids]]
cid = "*"
pricePerByte = 0.0000000001

# Explicit CID settings take precedence over the wildcard
[[cids]]
cid = "bafkreidj7dy2i5tnckivxbrdp6ija2m6lwcc6ivuttuxexezkfwgyorx7e"
pricePerByte = 0.0000000005

[[cids]]
cid = "bafkki48dk2001mcdqblhp6k6k3lhk0s00saa6d3jk2lkvipqf9dd00dlck"
pricePerByte = 0.0000000002

